libp2p/js-libp2p-tcp

package.json
src/index.js
tests/libp2p-tcp-test.js
tests/transport.js

**warning:** this PR introduces a new API that will trickle into interface-transport

multiple listeners, more tests, understand multiaddr on the listen function

---

README.md

Added (what I think is) the correct link to the `interface-connection` repo.

Fixing link in README.md

---

package.json
src/index.js
src/listener.js

To silence this warning:  
```
npm WARN deprecated lodash.contains@2.4.3: This package is discontinued. Use lodash.includes@^4.0.0.
```

Use lodash.includes instead of lodash.contains

---

.gitignore
README.md

Added a working example that listens at a given tcp address, dials the address, and prints the response before closing the listener.
Issue: https://github.com/libp2p/js-libp2p-tcp/issues/89

Fixing the broken example in README

---

src/get-multiaddr.js
src/listener.js
test/get-multiaddr.spec.js

Hello maintainers! I saw the remote vulnerability from js-ipfs #1447
and hunted it down. Are there any problems with or possible 
improvements to this proposed solution? I believe it will also resolve
js-libp2p-tcp issue #93 
Cheers,
Tom
--
Per the nodeJS documentation, a Net socket.remoteAddress value may
be undefined if the socket is destroyed, as by a client disconnect.
A multiaddr cannot be created for an invalid IP address (such as
the undefined remote address of a destroyed socket). Currently
the attempt results in a crash that can be triggered remotely. This
commit terminates processing of a destroyed socket before multiaddr
causes the crash.
fixes: https://github.com/libp2p/js-libp2p-tcp/issues/93
fixes: https://github.com/ipfs/js-ipfs/issues/1447

fix: "invalid ip address" "daemon can be crashed by remote user"

---

package.json
test/compliance.spec.js
test/filter.spec.js

Adds support for dialing over DNS. `mafmt` was previously limiting tcp addresses to only IP. An update was released to allow for DNS in mafmt@0.6.2. 
Resolves #95 
I used the example code mentioned in the issue, libp2p/js-libp2p-switch#277, to successfully connect to the ipfs jupiter node over dns via the following addresses:
/dns4/jupiter.i.ipfs.io/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx
/dnsaddr/jupiter.i.ipfs.io/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx
cc: @mgoelzer

feat: add support for dialing over dns

---

test/compliance.spec.js

In order to comply with this new standard rule ☺️ 
https://github.com/standard/eslint-config-standard/pull/133

Prefer const over let

---

.travis.yml
README.md
package.json
src/index.js
src/listener.js
test/adapter/listen-dial.spec.js
test/listen-dial.spec.js

Adds support to handle an array of multiaddrs on listen.
I also removed the ipfs id preservation. I'd like to get https://github.com/libp2p/js-libp2p/issues/323 implemented as a part of the async/await transition.
*Note*: This is being PRd into the async/await branch and not master.
I also added a fix for the IPv6 issue in Travis linux. resolves #105 
This could probably be a separate PR, but I added it here to avoid the need to rebase this and #102

feat: listen to array of multiaddrs

---

.gitignore
package.json
src/socket-to-conn.js
test/compliance.spec.js

The latest `interface-transport` includes tests to ensure timeline values are set properly. This exposed a bug where we did not set `close` when the socket ended without calling `close` on the MultiaddrConnection explicitly. This fixes that by listening for the close event on the socket from the start.
I removed `multiaddr('/dns4/ipfs.io')` from the compliance list of addresses. `filter` is now tested in `interface-transport` and it shows that this is not a valid TCP address. DNS addresses should be resolved into TCP addresses before being passed to the transport.

fix: ensure timeline.close is set

---

README.md

The Readme wasn't updated after the inclusion of the required `upgrader` option when creating a TCP instance. This corrects that.
ref: https://github.com/libp2p/js-libp2p-tcp/pull/112#discussion_r326123022

docs: add upgrader to readme example

---

package.json
src/index.js
src/listener.js
test/filter.spec.js
test/listen-dial.spec.js

This adds multiaddr 7 support to filtering, for the 0.13.x line. multiaddr 7 uses `p2p` instead of `ipfs`. Since we currently decapsulate with 'ipfs' this causes valid addresses to get filtered out. Filter will now check for `decapsulateCode` on the multiaddr and use that if it exists, otherwise it defaults to its previous behavior.

fix: support multiaddr 7

---

src/listener.js

This fixes logging for ephemeral address listening. Instead of logging `0.0.0.0:0`, this will log the actual local address and port.

fix: log the bound port and host

---

package.json
src/listener.js

Fixed per discussion on [libp2p/js-libp2p#523#discussion_r359997872](https://github.com/libp2p/js-libp2p/pull/523#discussion_r359997872)

fix: transport should not handle connection if upgradeInbound throws

---

src/listener.js

When upgrading sockets to MultiaddConnections, it's possible for an error to be thrown.
This can crash the application if a client disconnects prior to the listener
uprading the socket, as is likely occurring in #121. Errors will now be caught and logged
when attempting to upgrade the socket.
resolves #121

fix: catch thrown maConn errors in listener

---

src/listener.js

`MultiaddrConnection.close` can throw an error and we weren't catching that. We should be catching and logging for inbound connections, which this does. 
discovered at https://github.com/ipfs/js-ipfs/issues/2964

fix: catch error from maConn.close

---

package.json
test/connection.spec.js
test/filter.spec.js
test/listen-dial.spec.js

Upgrades to the latest multiaddrs with Uint8Arrays
Also removes redundant deps.
Depends on:
BREAKING CHANGES:
- The multiaddr dep used by this module returns Uint8Arrays and may
not be compatible with previous versions

chore: update deps

---

src/socket-to-conn.js
test/connection.spec.js

fix: hanging close promise

---

README.md

Links for `interface-transport` and `interface-connection` pointed to archived repos. This PR updates those links.

README: update interface-transport and interface-connection links

---

package.json
src/index.js

Closes #149 
New build looks like:
```
export = TCPWithIs;
declare const TCPWithIs: any;
declare namespace TCPWithIs {
export { Multiaddr, Connection, Upgrader, Listener, Socket };
}
type Multiaddr = import('multiaddr').Multiaddr;
type Connection = import("libp2p-interfaces/src/connection/connection");
type Upgrader = import('libp2p-interfaces/src/transport/types').Upgrader;
type Listener = import('libp2p-interfaces/src/transport/types').Listener;
type Socket = import('net').Socket;
//# sourceMappingURL=index.d.ts.map
```

fix: ts declaration export

---

package.json
src/index.ts
src/listener.ts
test/compliance.spec.ts
test/connection.spec.ts
test/filter.spec.ts
test/listen-dial.spec.ts

Updates to latest code from https://github.com/libp2p/js-libp2p-interfaces/pull/180

fix: update interfaces

---

test/compliance.spec.ts
test/listen-dial.spec.ts

Adds tests from #100 as the feature has been implemented already.

fix: add tests for ipv6 wildcard support

---

src/listener.ts

I observed a crash while running IPFS, need to do more investigation as to the cause but this is the fix.

fix: handle address being undefined

---

src/constants.ts
src/index.ts
src/listener.ts
src/socket-to-conn.ts
src/utils.ts
test/listen-dial.spec.ts

This PR adds the functionality to handle UNIX domain sockets.
* This works with plain `/unix` multiaddresses but is unable to handle p2p encapsulated addresses (`/unix/.../p2p/...`) due to ambiguity. Because of this it causes errors when attempting to use `/unix` addresses in js-libp2p because it appends the `/p2p` address.
* On Windows this uses named pipes instead.
Despite the fact that it does not work with `/unix` addresses in js-libp2p directly, this still remains useful and is needed in other projects like [js-libp2p-daemon](https://github.com/libp2p/js-libp2p-daemon).
This PR relates to issue #132.

feat: Unix domain sockets

---

src/index.ts
src/listener.ts

To allow more flexibility in use of sockets, expose options from node's net.connect method.

fix: expose extra options from net.connect for dial and listen

---

src/index.ts
src/listener.ts

From offline chat
> @dapplion - why doesn't the listener just use es6 syntax? Any reason to have to Object.assign? 
> @achingbrain - It was a straight port from previous versions, would merge a PR that uses more modern syntax

fix: port listener to ES6 class syntax

---

src/index.ts
src/listener.ts
test/maxConnections.spec.ts

https://nodejs.org/api/net.html#servermaxconnections
If set reject connections when the server's connection count gets high
Useful to prevent too resource exhaustion via many open connections on high bursts of activity

feat: add server.maxConnections option

---

README.md
package.json
src/index.ts
test/compliance.spec.ts
test/connection.spec.ts
test/filter.spec.ts
test/listen-dial.spec.ts
test/max-connections.spec.ts

`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major `@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of indirectly via `@libp2p/components`
Refs https://github.com/libp2p/js-libp2p-components/issues/6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection

fix!: remove @libp2p/components

---

src/listener.ts
test/listen-dial.spec.ts

The `net.Server` `.listen` callback is not a node-style callback that gets passed an error, it's a listener for the `listen` event.
To handle errors when `.listen`ing, one must listen for the `error` event, so update the code to do that and add a test to prevent regressions.

fix: handle listen error

---

package.json
src/index.ts
src/listener.ts
src/socket-to-conn.ts

Uses new metrics interface from https://github.com/libp2p/js-libp2p-interfaces/pull/310 to report useful connection metrics.
Similar to #217 but it adds the listening host/port to the metrics name to allow multiple TCP listeners to report metrics separately.
BREAKING CHANGE: requires metrics interface v4

feat!: add metrics

---

src/listener.ts

The [Prometheus metric naming guidelines](https://prometheus.io/docs/practices/naming/) say they should have suffixes like `_total` for unit-less counts and `_info` for metadata.

fix: update metric names to follow prometheus naming guide

---

test/filter.spec.ts

chore: add test for filtering unix socket address

---

.github/dependabot.yml
README.md
package.json

Ensure we get the right version of the module. Also updates project config to the latest version.

fix: make metrics interface a dep instead of a dev dep

---

src/index.ts
src/listener.ts
src/socket-to-conn.ts

Instead of inserting the interface address into the metric name, use the metric address as a label prefix for the value being reported.
This allows our metric names to be stable even if you don't know the ip/port combo that will be used ahead of time.
The tradeoff is the label names may change between restarts if the port number changes, but we have to apply a disambguator somewhere.
Depends on:

fix: use labels to differentiate interfaces for metrics

---

package.json
src/index.ts
src/socket-to-conn.ts
test/listen-dial.spec.ts

- Usage of abortable has a non-negligible cost, see https://github.com/libp2p/js-libp2p/issues/1420
I believe abortable is not necessary in this package, since we can kill the socket directly.

fix: remove abortable-iterator and close socket directly on abort

---

.gitignore
README.md
package.json

Publishes docs to gh-pages with links to external modules

fix: publish tsdocs for this module

---

package.json
src/index.ts
src/socket-to-conn.ts

Replaces [err-code](https://github.com/IndigoUnited/js-err-code/blob/master/index.js) with [CodeError](https://github.com/libp2p/js-libp2p-interfaces/pull/314)
Related: [js-libp2p#1269](https://github.com/libp2p/js-libp2p/issues/1269)
Changes
- removes err-code from dependencies
- adds @libp2p/interfaces@3.2.0 to dependencies
- uses CodeError in place of err-code

chore: replace err-code with CodeError

---

.gitignore
src/constants.ts

fix: increase default socket close timeout

---

src/index.ts
src/listener.ts
src/utils.ts
test/max-connections-close.spec.ts

- Extends https://github.com/libp2p/js-libp2p-tcp/pull/214
More resilient strategy to https://github.com/libp2p/js-libp2p-tcp/pull/213 which blocks new connections at the OS layer instead of at the app layer. Both features should exist since each has different tradeoffs. The approach of this PR is necessary for critical apps like Lodestar in highly adversarial environments. https://github.com/libp2p/js-libp2p-tcp/pull/213 is good for less critical situations, where the added complexity is not justified.

feat: close server on maxConnections

---

test/max-connections-close.spec.ts

github runners use ipv6 by default so if the server is listening on 127.0.0.1, then 127.0.0.1 needs to be explicitly dialed.

fix: specify host explicitly in node tests

---

src/socket-to-conn.ts

This was incorrectly logging as a timeout when it should be logging a close.
Also updates end event log for consistency with the other logging.

fix: update log message when socket closes

---

src/socket-to-conn.ts

**Motivation**
-  In `MultiaddrConnection.close()` it's not necessary to create a timer to finally destroy a socket if we call `socket.destroy()` already
**Description**
- Only create the timer if socket has something to write (`if (socket.writableLength > 0) {`)

fix: on MultiaddrConnection close() only create timer if needed

---

.gitignore
README.md
package.json

libp2p streams are now explicit about the types of sync/sources they provide, showing that they are `AsyncGenerator`s and not just `AsyncIterable`s.
Refs: https://github.com/achingbrain/it-stream-types/pull/45
BREAKING CHANGE: the type of the source/sink properties have changed

deps!: update stream types
